In [1]:
import pandas as pd
import sqlite3
import os

In [2]:
existing_data = pd.DataFrame({
    "name": ["Rahul", "Priya", "Arjun", "Sneha", "Kiran"],
    "email": [
        "rahul@gmail.com",
        "priya@gmail.com",
        "arjun@gmail.com",
        "sneha@gmail.com",
        "kiran@gmail.com"
    ],
    "city": ["Hyderabad", "Warangal", "Khammam", "Hyderabad", "Warangal"],
    "age": [22, 21, 23, 22, 24]
})

existing_data

    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1  Priya  priya@gmail.com   Warangal   21
2  Arjun  arjun@gmail.com    Khammam   23
3  Sneha  sneha@gmail.com  Hyderabad   22
4  Kiran  kiran@gmail.com   Warangal   24

In [3]:
new_data = pd.DataFrame({
    "name": ["Rahul", "Anu", "Priya", "Vamsi", "Kiran", "Meena"],
    "email": [
        "rahul@gmail.com",
        "anu@gmail.com",
        "priya@gmail.com",
        "vamsi@gmail.com",
        "kiran@gmail.com",
        "meena@gmail.com"
    ],
    "city": [
        "Hyderabad",
        "Khammam",
        "Warangal",
        "Hyderabad",
        "Warangal",
        "Khammam"
    ],
    "age": [22, 20, 21, 23, 24, 22]
})

new_data

    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1    Anu    anu@gmail.com    Khammam   20
2  Priya  priya@gmail.com   Warangal   21
3  Vamsi  vamsi@gmail.com  Hyderabad   23
4  Kiran  kiran@gmail.com   Warangal   24
5  Meena  meena@gmail.com    Khammam   22

In [4]:
print("Existing data:")
print(existing_data)

print("\nNew incoming data:")
print(new_data)

Existing data:
    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1  Priya  priya@gmail.com   Warangal   21
2  Arjun  arjun@gmail.com    Khammam   23
3  Sneha  sneha@gmail.com  Hyderabad   22
4  Kiran  kiran@gmail.com   Warangal   24

New incoming data:
    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1    Anu    anu@gmail.com    Khammam   20
2  Priya  priya@gmail.com   Warangal   21
3  Vamsi  vamsi@gmail.com  Hyderabad   23
4  Kiran  kiran@gmail.com   Warangal   24
5  Meena  meena@gmail.com    Khammam   22

In [5]:
print("Missing values in existing data:")
print(existing_data.isnull().sum())

print("\nMissing values in new data:")
print(new_data.isnull().sum())

Missing values in existing data:
name     0
email    0
city     0
age      0
dtype: int64

Missing values in new data:
name     0
email    0
city     0
age      0
dtype: int64

In [6]:
new_data = new_data.dropna()

print("New data after validation:")
print(new_data)

New data after validation:
    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1    Anu    anu@gmail.com    Khammam   20
2  Priya  priya@gmail.com   Warangal   21
3  Vamsi  vamsi@gmail.com  Hyderabad   23
4  Kiran  kiran@gmail.com   Warangal   24
5  Meena  meena@gmail.com    Khammam   22

In [7]:
before = len(new_data)

new_data = new_data.drop_duplicates()

after = len(new_data)

print("Records before duplicate removal:", before)
print("Records after duplicate removal:", after)
print("Duplicates removed:", before - after)

Records before duplicate removal: 6
Records after duplicate removal: 6
Duplicates removed: 0

In [8]:
duplicate_mask = new_data["email"].isin(existing_data["email"])

duplicate_data = new_data[duplicate_mask]

duplicate_data

    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
2  Priya  priya@gmail.com   Warangal   21
4  Kiran  kiran@gmail.com   Warangal   24

In [9]:
print("Duplicate / Redundant Records:")
print(duplicate_data)

Duplicate / Redundant Records:
    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
2  Priya  priya@gmail.com   Warangal   21
4  Kiran  kiran@gmail.com   Warangal   24

In [10]:
unique_data = new_data[~duplicate_mask]

print("Unique Records:")
print(unique_data)

Unique Records:
    name            email       city  age
1    Anu    anu@gmail.com    Khammam   20
3  Vamsi  vamsi@gmail.com  Hyderabad   23
5  Meena  meena@gmail.com    Khammam   22

In [11]:
print("Total incoming records:", len(new_data))
print("Duplicate records:", len(duplicate_data))
print("Unique records:", len(unique_data))

Total incoming records: 6
Duplicate records: 3
Unique records: 3

In [12]:
connection = sqlite3.connect("data_redundancy_database.db")

print("Database connected successfully.")

Database connected successfully.

In [13]:
existing_data.to_sql(
    "users",
    connection,
    if_exists="replace",
    index=False
)

print("Existing data stored in database.")

Existing data stored in database.

In [14]:
database_data = pd.read_sql_query(
    "SELECT * FROM users",
    connection
)

database_data

    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1  Priya  priya@gmail.com   Warangal   21
2  Arjun  arjun@gmail.com    Khammam   23
3  Sneha  sneha@gmail.com  Hyderabad   22
4  Kiran  kiran@gmail.com   Warangal   24

In [15]:
unique_data.to_sql(
    "users",
    connection,
    if_exists="append",
    index=False
)

print("Only unique and verified records added successfully.")

Only unique and verified records added successfully.

In [16]:
final_data = pd.read_sql_query(
    "SELECT * FROM users",
    connection
)

final_data

    name            email       city  age
0  Rahul  rahul@gmail.com  Hyderabad   22
1  Priya  priya@gmail.com   Warangal   21
2  Arjun  arjun@gmail.com    Khammam   23
3  Sneha  sneha@gmail.com  Hyderabad   22
4  Kiran  kiran@gmail.com   Warangal   24
5    Anu    anu@gmail.com    Khammam   20
6  Vamsi  vamsi@gmail.com  Hyderabad   23
7  Meena  meena@gmail.com    Khammam   22

In [17]:
duplicate_check = final_data[final_data.duplicated(
    subset=["email"],
    keep=False
)]

if duplicate_check.empty:
    print("SUCCESS: No duplicate email records found.")
else:
    print("Duplicate records found:")
    print(duplicate_check)

SUCCESS: No duplicate email records found.

In [18]:
initial_count = len(existing_data)
incoming_count = len(new_data)
duplicate_count = len(duplicate_data)
unique_count = len(unique_data)
final_count = len(final_data)

print("========== DATA REDUNDANCY REPORT ==========")
print("Initial database records :", initial_count)
print("Incoming records         :", incoming_count)
print("Duplicate records        :", duplicate_count)
print("Unique records added     :", unique_count)
print("Final database records   :", final_count)
print("============================================")

========== DATA REDUNDANCY REPORT ==========
Initial database records : 5
Incoming records         : 6
Duplicate records        : 3
Unique records added     : 3
Final database records   : 8
============================================

In [19]:
connection.close()

print("Database connection closed.")

Database connection closed.

In [20]:
existing_data.to_csv("existing_data.csv", index=False)
new_data.to_csv("new_data.csv", index=False)
unique_data.to_csv("unique_verified_data.csv", index=False)
duplicate_data.to_csv("duplicate_data.csv", index=False)

print("CSV files saved successfully.")

CSV files saved successfully.

In [21]:
print("Files created in the current folder:")

for file in os.listdir():
    if file.endswith((".csv", ".db", ".ipynb")):
        print(file)

Files created in the current folder:
 CODE THANU.ipynb
basics.ipynb
data frames.ipynb
datatypes.ipynb
data_immersion task2.ipynb
data_immersion task3.ipynb
data_redundancy_database.db
Data_Redundancy_Removal_System.ipynb
dhathrika code.ipynb
duplicate_data.csv
existing_data.csv
final_eda_dataset.csv
loops.ipynb
ml_pratice.ipynb
new_data.csv
NUMPY (1) (1) (1) (1).ipynb
numpypratice.ipynb
operators.ipynb
pandaspractice.ipynb
pandemic_spread_resource_forecasting_1000_rows.csv
pattern_pratice.ipynb
redundancy_summary_report.csv
redundant_records.csv
sales_analysis.db
Task_3_Final_Dataset.csv
unique_verified_data.csv
unique_verified_records.csv
Untitled.ipynb
Untitled1.ipynb
Untitled2.ipynb
whileloop.ipynb

In [22]:
summary = pd.DataFrame({
    "Metric": [
        "Initial Database Records",
        "Incoming Records",
        "Duplicate Records Rejected",
        "Unique Records Added",
        "Final Database Records"
    ],
    "Count": [
        initial_count,
        incoming_count,
        duplicate_count,
        unique_count,
        final_count
    ]
})

summary

                       Metric  Count
0    Initial Database Records      5
1            Incoming Records      6
2  Duplicate Records Rejected      3
3        Unique Records Added      3
4      Final Database Records      8

In [23]:
summary.to_csv("redundancy_summary_report.csv", index=False)

print("Redundancy summary report saved successfully.")

Redundancy summary report saved successfully.